/**
 * Merchant Database - Maps normalized merchant names to category/subcategory pairs.
 *
 * Lookup keys are lowercase, stripped of suffixes like "INC", "LLC", store numbers, etc.
 * The categorization engine normalizes incoming merchant strings before probing this map.
 */

export interface MerchantEntry {
  category: string;
  subcategory: string;
}

export const MERCHANT_DATABASE: Record<string, MerchantEntry> = {
  // ─── Streaming Services ──────────────────────────────────────────────
  netflix: { category: 'Entertainment', subcategory: 'Streaming Services' },
  hulu: { category: 'Entertainment', subcategory: 'Streaming Services' },
  'disney+': { category: 'Entertainment', subcategory: 'Streaming Services' },
  'disney plus': { category: 'Entertainment', subcategory: 'Streaming Services' },
  disneyplus: { category: 'Entertainment', subcategory: 'Streaming Services' },
  'hbo max': { category: 'Entertainment', subcategory: 'Streaming Services' },
  max: { category: 'Entertainment', subcategory: 'Streaming Services' },
  'amazon prime video': { category: 'Entertainment', subcategory: 'Streaming Services' },
  'prime video': { category: 'Entertainment', subcategory: 'Streaming Services' },
  peacock: { category: 'Entertainment', subcategory: 'Streaming Services' },
  'paramount+': { category: 'Entertainment', subcategory: 'Streaming Services' },
  'paramount plus': { category: 'Entertainment', subcategory: 'Streaming Services' },
  'apple tv+': { category: 'Entertainment', subcategory: 'Streaming Services' },
  'apple tv plus': { category: 'Entertainment', subcategory: 'Streaming Services' },
  crunchyroll: { category: 'Entertainment', subcategory: 'Streaming Services' },
  funimation: { category: 'Entertainment', subcategory: 'Streaming Services' },
  'discovery+': { category: 'Entertainment', subcategory: 'Streaming Services' },
  'espn+': { category: 'Entertainment', subcategory: 'Streaming Services' },
  'espn plus': { category: 'Entertainment', subcategory: 'Streaming Services' },
  'youtube premium': { category: 'Entertainment', subcategory: 'Streaming Services' },
  'youtube tv': { category: 'Entertainment', subcategory: 'Streaming Services' },
  'sling tv': { category: 'Entertainment', subcategory: 'Streaming Services' },
  fubo: { category: 'Entertainment', subcategory: 'Streaming Services' },
  fubotv: { category: 'Entertainment', subcategory: 'Streaming Services' },
  tubi: { category: 'Entertainment', subcategory: 'Streaming Services' },
  mubi: { category: 'Entertainment', subcategory: 'Streaming Services' },
  'criterion channel': { category: 'Entertainment', subcategory: 'Streaming Services' },
  shudder: { category: 'Entertainment', subcategory: 'Streaming Services' },
  'curiosity stream': { category: 'Entertainment', subcategory: 'Streaming Services' },
  britbox: { category: 'Entertainment', subcategory: 'Streaming Services' },
  starz: { category: 'Entertainment', subcategory: 'Streaming Services' },
  showtime: { category: 'Entertainment', subcategory: 'Streaming Services' },
  roku: { category: 'Entertainment', subcategory: 'Streaming Services' },
  plex: { category: 'Entertainment', subcategory: 'Streaming Services' },
  vudu: { category: 'Entertainment', subcategory: 'Streaming Services' },

  // ─── Music Streaming ─────────────────────────────────────────────────
  spotify: { category: 'Entertainment', subcategory: 'Music' },
  'apple music': { category: 'Entertainment', subcategory: 'Music' },
  tidal: { category: 'Entertainment', subcategory: 'Music' },
  pandora: { category: 'Entertainment', subcategory: 'Music' },
  deezer: { category: 'Entertainment', subcategory: 'Music' },
  'amazon music': { category: 'Entertainment', subcategory: 'Music' },
  soundcloud: { category: 'Entertainment', subcategory: 'Music' },
  'youtube music': { category: 'Entertainment', subcategory: 'Music' },
  'sirius xm': { category: 'Entertainment', subcategory: 'Music' },
  siriusxm: { category: 'Entertainment', subcategory: 'Music' },
  audible: { category: 'Entertainment', subcategory: 'Books' },

  // ─── Gaming ──────────────────────────────────────────────────────────
  steam: { category: 'Entertainment', subcategory: 'Games' },
  'valve software': { category: 'Entertainment', subcategory: 'Games' },
  playstation: { category: 'Entertainment', subcategory: 'Games' },
  'sony playstation': { category: 'Entertainment', subcategory: 'Games' },
  xbox: { category: 'Entertainment', subcategory: 'Games' },
  'xbox game pass': { category: 'Entertainment', subcategory: 'Games' },
  'microsoft xbox': { category: 'Entertainment', subcategory: 'Games' },
  nintendo: { category: 'Entertainment', subcategory: 'Games' },
  'epic games': { category: 'Entertainment', subcategory: 'Games' },
  'riot games': { category: 'Entertainment', subcategory: 'Games' },
  blizzard: { category: 'Entertainment', subcategory: 'Games' },
  'ea games': { category: 'Entertainment', subcategory: 'Games' },
  'electronic arts': { category: 'Entertainment', subcategory: 'Games' },
  roblox: { category: 'Entertainment', subcategory: 'Games' },
  twitch: { category: 'Entertainment', subcategory: 'Games' },

  // ─── Movies & Theater ────────────────────────────────────────────────
  'amc theatres': { category: 'Entertainment', subcategory: 'Movies & Theater' },
  amc: { category: 'Entertainment', subcategory: 'Movies & Theater' },
  'regal cinemas': { category: 'Entertainment', subcategory: 'Movies & Theater' },
  regal: { category: 'Entertainment', subcategory: 'Movies & Theater' },
  cinemark: { category: 'Entertainment', subcategory: 'Movies & Theater' },
  fandango: { category: 'Entertainment', subcategory: 'Movies & Theater' },
  imax: { category: 'Entertainment', subcategory: 'Movies & Theater' },
  'alamo drafthouse': { category: 'Entertainment', subcategory: 'Movies & Theater' },

  // ─── Food Delivery ───────────────────────────────────────────────────
  doordash: { category: 'Food & Drink', subcategory: 'Restaurants' },
  'uber eats': { category: 'Food & Drink', subcategory: 'Restaurants' },
  ubereats: { category: 'Food & Drink', subcategory: 'Restaurants' },
  grubhub: { category: 'Food & Drink', subcategory: 'Restaurants' },
  postmates: { category: 'Food & Drink', subcategory: 'Restaurants' },
  instacart: { category: 'Food & Drink', subcategory: 'Groceries' },
  seamless: { category: 'Food & Drink', subcategory: 'Restaurants' },
  caviar: { category: 'Food & Drink', subcategory: 'Restaurants' },
  gopuff: { category: 'Food & Drink', subcategory: 'Groceries' },
  shipt: { category: 'Food & Drink', subcategory: 'Groceries' },
  freshly: { category: 'Food & Drink', subcategory: 'Groceries' },
  hungryroot: { category: 'Food & Drink', subcategory: 'Groceries' },
  'factor meals': { category: 'Food & Drink', subcategory: 'Groceries' },
  factor: { category: 'Food & Drink', subcategory: 'Groceries' },
  'hello fresh': { category: 'Food & Drink', subcategory: 'Groceries' },
  hellofresh: { category: 'Food & Drink', subcategory: 'Groceries' },
  'blue apron': { category: 'Food & Drink', subcategory: 'Groceries' },
  'home chef': { category: 'Food & Drink', subcategory: 'Groceries' },
  sunbasket: { category: 'Food & Drink', subcategory: 'Groceries' },
  'daily harvest': { category: 'Food & Drink', subcategory: 'Groceries' },

  // ─── Fast Food ───────────────────────────────────────────────────────
  mcdonalds: { category: 'Food & Drink', subcategory: 'Fast Food' },
  "mcdonald's": { category: 'Food & Drink', subcategory: 'Fast Food' },
  'burger king': { category: 'Food & Drink', subcategory: 'Fast Food' },
  wendys: { category: 'Food & Drink', subcategory: 'Fast Food' },
  "wendy's": { category: 'Food & Drink', subcategory: 'Fast Food' },
  'taco bell': { category: 'Food & Drink', subcategory: 'Fast Food' },
  'chick-fil-a': { category: 'Food & Drink', subcategory: 'Fast Food' },
  chickfila: { category: 'Food & Drink', subcategory: 'Fast Food' },
  'chick fil a': { category: 'Food & Drink', subcategory: 'Fast Food' },
  subway: { category: 'Food & Drink', subcategory: 'Fast Food' },
  dominos: { category: 'Food & Drink', subcategory: 'Fast Food' },
  "domino's": { category: 'Food & Drink', subcategory: 'Fast Food' },
  'pizza hut': { category: 'Food & Drink', subcategory: 'Fast Food' },
  'papa johns': { category: 'Food & Drink', subcategory: 'Fast Food' },
  "papa john's": { category: 'Food & Drink', subcategory: 'Fast Food' },
  'little caesars': { category: 'Food & Drink', subcategory: 'Fast Food' },
  kfc: { category: 'Food & Drink', subcategory: 'Fast Food' },
  popeyes: { category: 'Food & Drink', subcategory: 'Fast Food' },
  'sonic drive-in': { category: 'Food & Drink', subcategory: 'Fast Food' },
  sonic: { category: 'Food & Drink', subcategory: 'Fast Food' },
  "arby's": { category: 'Food & Drink', subcategory: 'Fast Food' },
  arbys: { category: 'Food & Drink', subcategory: 'Fast Food' },
  'jack in the box': { category: 'Food & Drink', subcategory: 'Fast Food' },
  whataburger: { category: 'Food & Drink', subcategory: 'Fast Food' },
  'in-n-out': { category: 'Food & Drink', subcategory: 'Fast Food' },
  'in n out': { category: 'Food & Drink', subcategory: 'Fast Food' },
  'five guys': { category: 'Food & Drink', subcategory: 'Fast Food' },
  'shake shack': { category: 'Food & Drink', subcategory: 'Fast Food' },
  chipotle: { category: 'Food & Drink', subcategory: 'Fast Food' },
  panera: { category: 'Food & Drink', subcategory: 'Fast Food' },
  'panera bread': { category: 'Food & Drink', subcategory: 'Fast Food' },
  'panda express': { category: 'Food & Drink', subcategory: 'Fast Food' },
  wingstop: { category: 'Food & Drink', subcategory: 'Fast Food' },
  'raising canes': { category: 'Food & Drink', subcategory: 'Fast Food' },
  "raising cane's": { category: 'Food & Drink', subcategory: 'Fast Food' },
  culvers: { category: 'Food & Drink', subcategory: 'Fast Food' },
  "culver's": { category: 'Food & Drink', subcategory: 'Fast Food' },
  'del taco': { category: 'Food & Drink', subcategory: 'Fast Food' },
  'jersey mikes': { category: 'Food & Drink', subcategory: 'Fast Food' },
  "jersey mike's": { category: 'Food & Drink', subcategory: 'Fast Food' },
  'firehouse subs': { category: 'Food & Drink', subcategory: 'Fast Food' },
  'jimmy johns': { category: 'Food & Drink', subcategory: 'Fast Food' },
  "jimmy john's": { category: 'Food & Drink', subcategory: 'Fast Food' },
  zaxbys: { category: 'Food & Drink', subcategory: 'Fast Food' },
  "zaxby's": { category: 'Food & Drink', subcategory: 'Fast Food' },
  'noodles and company': { category: 'Food & Drink', subcategory: 'Fast Food' },
  qdoba: { category: 'Food & Drink', subcategory: 'Fast Food' },
  'moes southwest grill': { category: 'Food & Drink', subcategory: 'Fast Food' },

  // ─── Coffee Shops ────────────────────────────────────────────────────
  starbucks: { category: 'Food & Drink', subcategory: 'Coffee Shops' },
  dunkin: { category: 'Food & Drink', subcategory: 'Coffee Shops' },
  'dunkin donuts': { category: 'Food & Drink', subcategory: 'Coffee Shops' },
  "dunkin'": { category: 'Food & Drink', subcategory: 'Coffee Shops' },
  'peets coffee': { category: 'Food & Drink', subcategory: 'Coffee Shops' },
  "peet's coffee": { category: 'Food & Drink', subcategory: 'Coffee Shops' },
  'dutch bros': { category: 'Food & Drink', subcategory: 'Coffee Shops' },
  'tim hortons': { category: 'Food & Drink', subcategory: 'Coffee Shops' },
  'caribou coffee': { category: 'Food & Drink', subcategory: 'Coffee Shops' },
  'philz coffee': { category: 'Food & Drink', subcategory: 'Coffee Shops' },
  'blue bottle coffee': { category: 'Food & Drink', subcategory: 'Coffee Shops' },
  intelligentsia: { category: 'Food & Drink', subcategory: 'Coffee Shops' },
  'coffee bean': { category: 'Food & Drink', subcategory: 'Coffee Shops' },
  'la colombe': { category: 'Food & Drink', subcategory: 'Coffee Shops' },

  // ─── Restaurants (Casual/Sit-Down) ───────────────────────────────────
  'olive garden': { category: 'Food & Drink', subcategory: 'Restaurants' },
  applebees: { category: 'Food & Drink', subcategory: 'Restaurants' },
  "applebee's": { category: 'Food & Drink', subcategory: 'Restaurants' },
  chilis: { category: 'Food & Drink', subcategory: 'Restaurants' },
  "chili's": { category: 'Food & Drink', subcategory: 'Restaurants' },
  'outback steakhouse': { category: 'Food & Drink', subcategory: 'Restaurants' },
  'red lobster': { category: 'Food & Drink', subcategory: 'Restaurants' },
  'texas roadhouse': { category: 'Food & Drink', subcategory: 'Restaurants' },
  'longhorn steakhouse': { category: 'Food & Drink', subcategory: 'Restaurants' },
  'cracker barrel': { category: 'Food & Drink', subcategory: 'Restaurants' },
  ihop: { category: 'Food & Drink', subcategory: 'Restaurants' },
  dennys: { category: 'Food & Drink', subcategory: 'Restaurants' },
  "denny's": { category: 'Food & Drink', subcategory: 'Restaurants' },
  'waffle house': { category: 'Food & Drink', subcategory: 'Restaurants' },
  'cheesecake factory': { category: 'Food & Drink', subcategory: 'Restaurants' },
  'the cheesecake factory': { category: 'Food & Drink', subcategory: 'Restaurants' },
  'red robin': { category: 'Food & Drink', subcategory: 'Restaurants' },
  'buffalo wild wings': { category: 'Food & Drink', subcategory: 'Restaurants' },
  'tgi fridays': { category: 'Food & Drink', subcategory: 'Restaurants' },
  "tgi friday's": { category: 'Food & Drink', subcategory: 'Restaurants' },
  "bj's restaurant": { category: 'Food & Drink', subcategory: 'Restaurants' },
  "cheddar's": { category: 'Food & Drink', subcategory: 'Restaurants' },
  'bob evans': { category: 'Food & Drink', subcategory: 'Restaurants' },
  'golden corral': { category: 'Food & Drink', subcategory: 'Restaurants' },
  sweetgreen: { category: 'Food & Drink', subcategory: 'Restaurants' },
  cava: { category: 'Food & Drink', subcategory: 'Restaurants' },

  // ─── Bars & Alcohol ──────────────────────────────────────────────────
  'total wine': { category: 'Food & Drink', subcategory: 'Bars & Alcohol' },
  "binny's": { category: 'Food & Drink', subcategory: 'Bars & Alcohol' },
  binnys: { category: 'Food & Drink', subcategory: 'Bars & Alcohol' },
  "spec's": { category: 'Food & Drink', subcategory: 'Bars & Alcohol' },
  bevmo: { category: 'Food & Drink', subcategory: 'Bars & Alcohol' },
  drizly: { category: 'Food & Drink', subcategory: 'Bars & Alcohol' },
  'wine.com': { category: 'Food & Drink', subcategory: 'Bars & Alcohol' },
  'liquor store': { category: 'Food & Drink', subcategory: 'Bars & Alcohol' },

  // ─── Grocery Stores ──────────────────────────────────────────────────
  'walmart grocery': { category: 'Food & Drink', subcategory: 'Groceries' },
  kroger: { category: 'Food & Drink', subcategory: 'Groceries' },
  safeway: { category: 'Food & Drink', subcategory: 'Groceries' },
  albertsons: { category: 'Food & Drink', subcategory: 'Groceries' },
  publix: { category: 'Food & Drink', subcategory: 'Groceries' },
  'whole foods': { category: 'Food & Drink', subcategory: 'Groceries' },
  'whole foods market': { category: 'Food & Drink', subcategory: 'Groceries' },
  'trader joes': { category: 'Food & Drink', subcategory: 'Groceries' },
  "trader joe's": { category: 'Food & Drink', subcategory: 'Groceries' },
  aldi: { category: 'Food & Drink', subcategory: 'Groceries' },
  lidl: { category: 'Food & Drink', subcategory: 'Groceries' },
  'food lion': { category: 'Food & Drink', subcategory: 'Groceries' },
  'stop and shop': { category: 'Food & Drink', subcategory: 'Groceries' },
  'stop & shop': { category: 'Food & Drink', subcategory: 'Groceries' },
  giant: { category: 'Food & Drink', subcategory: 'Groceries' },
  'giant eagle': { category: 'Food & Drink', subcategory: 'Groceries' },
  heb: { category: 'Food & Drink', subcategory: 'Groceries' },
  'h-e-b': { category: 'Food & Drink', subcategory: 'Groceries' },
  meijer: { category: 'Food & Drink', subcategory: 'Groceries' },
  wegmans: { category: 'Food & Drink', subcategory: 'Groceries' },
  sprouts: { category: 'Food & Drink', subcategory: 'Groceries' },
  'sprouts farmers market': { category: 'Food & Drink', subcategory: 'Groceries' },
  'fresh market': { category: 'Food & Drink', subcategory: 'Groceries' },
  'the fresh market': { category: 'Food & Drink', subcategory: 'Groceries' },
  'harris teeter': { category: 'Food & Drink', subcategory: 'Groceries' },
  'winn-dixie': { category: 'Food & Drink', subcategory: 'Groceries' },
  'winn dixie': { category: 'Food & Drink', subcategory: 'Groceries' },
  'piggly wiggly': { category: 'Food & Drink', subcategory: 'Groceries' },
  "fry's food": { category: 'Food & Drink', subcategory: 'Groceries' },
  ralphs: { category: 'Food & Drink', subcategory: 'Groceries' },
  vons: { category: 'Food & Drink', subcategory: 'Groceries' },
  'market basket': { category: 'Food & Drink', subcategory: 'Groceries' },
  shoprite: { category: 'Food & Drink', subcategory: 'Groceries' },
  'food city': { category: 'Food & Drink', subcategory: 'Groceries' },
  'hy-vee': { category: 'Food & Drink', subcategory: 'Groceries' },
  hyvee: { category: 'Food & Drink', subcategory: 'Groceries' },
  'king soopers': { category: 'Food & Drink', subcategory: 'Groceries' },
  "smith's": { category: 'Food & Drink', subcategory: 'Groceries' },
  'jewel-osco': { category: 'Food & Drink', subcategory: 'Groceries' },
  'acme markets': { category: 'Food & Drink', subcategory: 'Groceries' },
  hannaford: { category: 'Food & Drink', subcategory: 'Groceries' },
  winco: { category: 'Food & Drink', subcategory: 'Groceries' },
  'grocery outlet': { category: 'Food & Drink', subcategory: 'Groceries' },
  costco: { category: 'Food & Drink', subcategory: 'Groceries' },
  'sams club': { category: 'Food & Drink', subcategory: 'Groceries' },
  "sam's club": { category: 'Food & Drink', subcategory: 'Groceries' },
  'bjs wholesale': { category: 'Food & Drink', subcategory: 'Groceries' },

  // ─── Ride Share ──────────────────────────────────────────────────────
  uber: { category: 'Transportation', subcategory: 'Ride Share' },
  lyft: { category: 'Transportation', subcategory: 'Ride Share' },
  via: { category: 'Transportation', subcategory: 'Ride Share' },

  // ─── Gas Stations ────────────────────────────────────────────────────
  shell: { category: 'Transportation', subcategory: 'Gas & Fuel' },
  'shell oil': { category: 'Transportation', subcategory: 'Gas & Fuel' },
  exxon: { category: 'Transportation', subcategory: 'Gas & Fuel' },
  exxonmobil: { category: 'Transportation', subcategory: 'Gas & Fuel' },
  mobil: { category: 'Transportation', subcategory: 'Gas & Fuel' },
  chevron: { category: 'Transportation', subcategory: 'Gas & Fuel' },
  bp: { category: 'Transportation', subcategory: 'Gas & Fuel' },
  marathon: { category: 'Transportation', subcategory: 'Gas & Fuel' },
  'marathon petroleum': { category: 'Transportation', subcategory: 'Gas & Fuel' },
  sunoco: { category: 'Transportation', subcategory: 'Gas & Fuel' },
  valero: { category: 'Transportation', subcategory: 'Gas & Fuel' },
  citgo: { category: 'Transportation', subcategory: 'Gas & Fuel' },
  'phillips 66': { category: 'Transportation', subcategory: 'Gas & Fuel' },
  conoco: { category: 'Transportation', subcategory: 'Gas & Fuel' },
  sinclair: { category: 'Transportation', subcategory: 'Gas & Fuel' },
  arco: { category: 'Transportation', subcategory: 'Gas & Fuel' },
  speedway: { category: 'Transportation', subcategory: 'Gas & Fuel' },
  'murphy usa': { category: 'Transportation', subcategory: 'Gas & Fuel' },
  wawa: { category: 'Transportation', subcategory: 'Gas & Fuel' },
  sheetz: { category: 'Transportation', subcategory: 'Gas & Fuel' },
  quiktrip: { category: 'Transportation', subcategory: 'Gas & Fuel' },
  qt: { category: 'Transportation', subcategory: 'Gas & Fuel' },
  racetrac: { category: 'Transportation', subcategory: 'Gas & Fuel' },
  "casey's": { category: 'Transportation', subcategory: 'Gas & Fuel' },
  caseys: { category: 'Transportation', subcategory: 'Gas & Fuel' },
  'pilot flying j': { category: 'Transportation', subcategory: 'Gas & Fuel' },
  'pilot travel center': { category: 'Transportation', subcategory: 'Gas & Fuel' },
  'loves travel stop': { category: 'Transportation', subcategory: 'Gas & Fuel' },
  'ta travel center': { category: 'Transportation', subcategory: 'Gas & Fuel' },
  'circle k': { category: 'Transportation', subcategory: 'Gas & Fuel' },
  '7-eleven gas': { category: 'Transportation', subcategory: 'Gas & Fuel' },
  'cumberland farms': { category: 'Transportation', subcategory: 'Gas & Fuel' },
  'kwik trip': { category: 'Transportation', subcategory: 'Gas & Fuel' },
  thorntons: { category: 'Transportation', subcategory: 'Gas & Fuel' },
  getgo: { category: 'Transportation', subcategory: 'Gas & Fuel' },
  'buc-ees': { category: 'Transportation', subcategory: 'Gas & Fuel' },
  "buc-ee's": { category: 'Transportation', subcategory: 'Gas & Fuel' },
  'tesla supercharger': { category: 'Transportation', subcategory: 'Gas & Fuel' },
  chargepoint: { category: 'Transportation', subcategory: 'Gas & Fuel' },
  'electrify america': { category: 'Transportation', subcategory: 'Gas & Fuel' },
  evgo: { category: 'Transportation', subcategory: 'Gas & Fuel' },

  // ─── Public Transit ──────────────────────────────────────────────────
  mta: { category: 'Transportation', subcategory: 'Public Transit' },
  metro: { category: 'Transportation', subcategory: 'Public Transit' },
  bart: { category: 'Transportation', subcategory: 'Public Transit' },
  cta: { category: 'Transportation', subcategory: 'Public Transit' },
  wmata: { category: 'Transportation', subcategory: 'Public Transit' },
  septa: { category: 'Transportation', subcategory: 'Public Transit' },
  mbta: { category: 'Transportation', subcategory: 'Public Transit' },
  'nj transit': { category: 'Transportation', subcategory: 'Public Transit' },
  amtrak: { category: 'Transportation', subcategory: 'Public Transit' },
  greyhound: { category: 'Transportation', subcategory: 'Public Transit' },
  megabus: { category: 'Transportation', subcategory: 'Public Transit' },
  flixbus: { category: 'Transportation', subcategory: 'Public Transit' },

  // ─── Parking ─────────────────────────────────────────────────────────
  spothero: { category: 'Transportation', subcategory: 'Parking' },
  parkwhiz: { category: 'Transportation', subcategory: 'Parking' },
  parkopedia: { category: 'Transportation', subcategory: 'Parking' },
  parkme: { category: 'Transportation', subcategory: 'Parking' },
  parkmobile: { category: 'Transportation', subcategory: 'Parking' },
  'laz parking': { category: 'Transportation', subcategory: 'Parking' },
  'sp plus': { category: 'Transportation', subcategory: 'Parking' },

  // ─── Auto Insurance ──────────────────────────────────────────────────
  geico: { category: 'Transportation', subcategory: 'Auto Insurance' },
  'state farm': { category: 'Transportation', subcategory: 'Auto Insurance' },
  progressive: { category: 'Transportation', subcategory: 'Auto Insurance' },
  allstate: { category: 'Transportation', subcategory: 'Auto Insurance' },
  usaa: { category: 'Transportation', subcategory: 'Auto Insurance' },
  'liberty mutual': { category: 'Transportation', subcategory: 'Auto Insurance' },
  nationwide: { category: 'Transportation', subcategory: 'Auto Insurance' },
  'farmers insurance': { category: 'Transportation', subcategory: 'Auto Insurance' },
  'root insurance': { category: 'Transportation', subcategory: 'Auto Insurance' },

  // ─── Auto Maintenance ────────────────────────────────────────────────
  autozone: { category: 'Transportation', subcategory: 'Auto Maintenance' },
  'oreilly auto': { category: 'Transportation', subcategory: 'Auto Maintenance' },
  "o'reilly auto": { category: 'Transportation', subcategory: 'Auto Maintenance' },
  'advance auto parts': { category: 'Transportation', subcategory: 'Auto Maintenance' },
  'napa auto parts': { category: 'Transportation', subcategory: 'Auto Maintenance' },
  'jiffy lube': { category: 'Transportation', subcategory: 'Auto Maintenance' },
  valvoline: { category: 'Transportation', subcategory: 'Auto Maintenance' },
  midas: { category: 'Transportation', subcategory: 'Auto Maintenance' },
  'pep boys': { category: 'Transportation', subcategory: 'Auto Maintenance' },
  firestone: { category: 'Transportation', subcategory: 'Auto Maintenance' },
  goodyear: { category: 'Transportation', subcategory: 'Auto Maintenance' },
  'discount tire': { category: 'Transportation', subcategory: 'Auto Maintenance' },
  'tire rack': { category: 'Transportation', subcategory: 'Auto Maintenance' },
  safelite: { category: 'Transportation', subcategory: 'Auto Maintenance' },
  maaco: { category: 'Transportation', subcategory: 'Auto Maintenance' },
  meineke: { category: 'Transportation', subcategory: 'Auto Maintenance' },
  'christian brothers': { category: 'Transportation', subcategory: 'Auto Maintenance' },
  'take 5 oil change': { category: 'Transportation', subcategory: 'Auto Maintenance' },
  'car wash': { category: 'Transportation', subcategory: 'Auto Maintenance' },

  // ─── General Retail ──────────────────────────────────────────────────
  amazon: { category: 'Shopping', subcategory: 'Online Shopping' },
  'amazon.com': { category: 'Shopping', subcategory: 'Online Shopping' },
  amzn: { category: 'Shopping', subcategory: 'Online Shopping' },
  'amazon prime': { category: 'Shopping', subcategory: 'Online Shopping' },
  walmart: { category: 'Shopping', subcategory: 'Home Goods' },
  target: { category: 'Shopping', subcategory: 'Home Goods' },
  'dollar general': { category: 'Shopping', subcategory: 'Home Goods' },
  'dollar tree': { category: 'Shopping', subcategory: 'Home Goods' },
  'family dollar': { category: 'Shopping', subcategory: 'Home Goods' },
  'five below': { category: 'Shopping', subcategory: 'Home Goods' },
  'big lots': { category: 'Shopping', subcategory: 'Home Goods' },
  'bed bath and beyond': { category: 'Shopping', subcategory: 'Home Goods' },
  'tuesday morning': { category: 'Shopping', subcategory: 'Home Goods' },
  homegoods: { category: 'Shopping', subcategory: 'Home Goods' },
  marshalls: { category: 'Shopping', subcategory: 'Home Goods' },
  'tj maxx': { category: 'Shopping', subcategory: 'Home Goods' },
  tjmaxx: { category: 'Shopping', subcategory: 'Home Goods' },
  ross: { category: 'Shopping', subcategory: 'Home Goods' },
  'ross dress for less': { category: 'Shopping', subcategory: 'Home Goods' },
  burlington: { category: 'Shopping', subcategory: 'Home Goods' },
  ikea: { category: 'Shopping', subcategory: 'Home Goods' },
  'pier 1': { category: 'Shopping', subcategory: 'Home Goods' },
  'pottery barn': { category: 'Shopping', subcategory: 'Home Goods' },
  'crate and barrel': { category: 'Shopping', subcategory: 'Home Goods' },
  'crate & barrel': { category: 'Shopping', subcategory: 'Home Goods' },
  'west elm': { category: 'Shopping', subcategory: 'Home Goods' },
  'williams sonoma': { category: 'Shopping', subcategory: 'Home Goods' },
  'williams-sonoma': { category: 'Shopping', subcategory: 'Home Goods' },
  wayfair: { category: 'Shopping', subcategory: 'Home Goods' },
  overstock: { category: 'Shopping', subcategory: 'Home Goods' },

  // ─── Clothing ────────────────────────────────────────────────────────
  nike: { category: 'Shopping', subcategory: 'Clothing' },
  adidas: { category: 'Shopping', subcategory: 'Clothing' },
  gap: { category: 'Shopping', subcategory: 'Clothing' },
  'old navy': { category: 'Shopping', subcategory: 'Clothing' },
  'banana republic': { category: 'Shopping', subcategory: 'Clothing' },
  'h&m': { category: 'Shopping', subcategory: 'Clothing' },
  zara: { category: 'Shopping', subcategory: 'Clothing' },
  uniqlo: { category: 'Shopping', subcategory: 'Clothing' },
  'forever 21': { category: 'Shopping', subcategory: 'Clothing' },
  nordstrom: { category: 'Shopping', subcategory: 'Clothing' },
  macys: { category: 'Shopping', subcategory: 'Clothing' },
  "macy's": { category: 'Shopping', subcategory: 'Clothing' },
  jcpenney: { category: 'Shopping', subcategory: 'Clothing' },
  'j.c. penney': { category: 'Shopping', subcategory: 'Clothing' },
  kohls: { category: 'Shopping', subcategory: 'Clothing' },
  "kohl's": { category: 'Shopping', subcategory: 'Clothing' },
  lululemon: { category: 'Shopping', subcategory: 'Clothing' },
  'american eagle': { category: 'Shopping', subcategory: 'Clothing' },
  aeropostale: { category: 'Shopping', subcategory: 'Clothing' },
  express: { category: 'Shopping', subcategory: 'Clothing' },
  'ralph lauren': { category: 'Shopping', subcategory: 'Clothing' },
  'brooks brothers': { category: 'Shopping', subcategory: 'Clothing' },
  'j.crew': { category: 'Shopping', subcategory: 'Clothing' },
  'j crew': { category: 'Shopping', subcategory: 'Clothing' },
  abercrombie: { category: 'Shopping', subcategory: 'Clothing' },
  'abercrombie & fitch': { category: 'Shopping', subcategory: 'Clothing' },
  patagonia: { category: 'Shopping', subcategory: 'Clothing' },
  'the north face': { category: 'Shopping', subcategory: 'Clothing' },
  'under armour': { category: 'Shopping', subcategory: 'Clothing' },
  'foot locker': { category: 'Shopping', subcategory: 'Clothing' },
  'finish line': { category: 'Shopping', subcategory: 'Clothing' },
  skechers: { category: 'Shopping', subcategory: 'Clothing' },
  'new balance': { category: 'Shopping', subcategory: 'Clothing' },
  puma: { category: 'Shopping', subcategory: 'Clothing' },
  shein: { category: 'Shopping', subcategory: 'Clothing' },
  'stitch fix': { category: 'Shopping', subcategory: 'Clothing' },
  'rent the runway': { category: 'Shopping', subcategory: 'Clothing' },
  torrid: { category: 'Shopping', subcategory: 'Clothing' },
  'lane bryant': { category: 'Shopping', subcategory: 'Clothing' },
  "victoria's secret": { category: 'Shopping', subcategory: 'Clothing' },
  'victorias secret': { category: 'Shopping', subcategory: 'Clothing' },
  'bath and body works': { category: 'Shopping', subcategory: 'Clothing' },
  'bath & body works': { category: 'Shopping', subcategory: 'Clothing' },

  // ─── Electronics ─────────────────────────────────────────────────────
  apple: { category: 'Shopping', subcategory: 'Electronics' },
  'apple store': { category: 'Shopping', subcategory: 'Electronics' },
  'apple.com': { category: 'Shopping', subcategory: 'Electronics' },
  'best buy': { category: 'Shopping', subcategory: 'Electronics' },
  bestbuy: { category: 'Shopping', subcategory: 'Electronics' },
  microcenter: { category: 'Shopping', subcategory: 'Electronics' },
  'micro center': { category: 'Shopping', subcategory: 'Electronics' },
  'b&h photo': { category: 'Shopping', subcategory: 'Electronics' },
  newegg: { category: 'Shopping', subcategory: 'Electronics' },
  samsung: { category: 'Shopping', subcategory: 'Electronics' },
  dell: { category: 'Shopping', subcategory: 'Electronics' },
  'hp store': { category: 'Shopping', subcategory: 'Electronics' },
  lenovo: { category: 'Shopping', subcategory: 'Electronics' },
  gamestop: { category: 'Shopping', subcategory: 'Electronics' },
  radioshack: { category: 'Shopping', subcategory: 'Electronics' },

  // ─── Hardware & Home Improvement ─────────────────────────────────────
  'home depot': { category: 'Housing', subcategory: 'Home Improvement' },
  'the home depot': { category: 'Housing', subcategory: 'Home Improvement' },
  lowes: { category: 'Housing', subcategory: 'Home Improvement' },
  "lowe's": { category: 'Housing', subcategory: 'Home Improvement' },
  menards: { category: 'Housing', subcategory: 'Home Improvement' },
  'ace hardware': { category: 'Housing', subcategory: 'Home Improvement' },
  'true value': { category: 'Housing', subcategory: 'Home Improvement' },
  'harbor freight': { category: 'Housing', subcategory: 'Home Improvement' },
  'sherwin williams': { category: 'Housing', subcategory: 'Home Improvement' },
  'sherwin-williams': { category: 'Housing', subcategory: 'Home Improvement' },
  'benjamin moore': { category: 'Housing', subcategory: 'Home Improvement' },

  // ─── Utilities ───────────────────────────────────────────────────────
  comcast: { category: 'Utilities', subcategory: 'Internet' },
  xfinity: { category: 'Utilities', subcategory: 'Internet' },
  spectrum: { category: 'Utilities', subcategory: 'Internet' },
  'at&t': { category: 'Utilities', subcategory: 'Phone' },
  att: { category: 'Utilities', subcategory: 'Phone' },
  verizon: { category: 'Utilities', subcategory: 'Phone' },
  't-mobile': { category: 'Utilities', subcategory: 'Phone' },
  tmobile: { category: 'Utilities', subcategory: 'Phone' },
  sprint: { category: 'Utilities', subcategory: 'Phone' },
  'mint mobile': { category: 'Utilities', subcategory: 'Phone' },
  visible: { category: 'Utilities', subcategory: 'Phone' },
  'google fi': { category: 'Utilities', subcategory: 'Phone' },
  'cricket wireless': { category: 'Utilities', subcategory: 'Phone' },
  'boost mobile': { category: 'Utilities', subcategory: 'Phone' },
  'metro by t-mobile': { category: 'Utilities', subcategory: 'Phone' },
  'us cellular': { category: 'Utilities', subcategory: 'Phone' },
  'cox communications': { category: 'Utilities', subcategory: 'Internet' },
  centurylink: { category: 'Utilities', subcategory: 'Internet' },
  frontier: { category: 'Utilities', subcategory: 'Internet' },
  optimum: { category: 'Utilities', subcategory: 'Internet' },
  windstream: { category: 'Utilities', subcategory: 'Internet' },
  hughesnet: { category: 'Utilities', subcategory: 'Internet' },
  starlink: { category: 'Utilities', subcategory: 'Internet' },
  'google fiber': { category: 'Utilities', subcategory: 'Internet' },
  'dish network': { category: 'Utilities', subcategory: 'Internet' },
  directv: { category: 'Utilities', subcategory: 'Internet' },
  'duke energy': { category: 'Utilities', subcategory: 'Electric' },
  'pacific gas': { category: 'Utilities', subcategory: 'Electric' },
  'pg&e': { category: 'Utilities', subcategory: 'Electric' },
  'southern california edison': { category: 'Utilities', subcategory: 'Electric' },
  'con edison': { category: 'Utilities', subcategory: 'Electric' },
  coned: { category: 'Utilities', subcategory: 'Electric' },
  'dominion energy': { category: 'Utilities', subcategory: 'Electric' },
  'florida power': { category: 'Utilities', subcategory: 'Electric' },
  entergy: { category: 'Utilities', subcategory: 'Electric' },
  'xcel energy': { category: 'Utilities', subcategory: 'Electric' },
  firstenergy: { category: 'Utilities', subcategory: 'Electric' },
  'national grid': { category: 'Utilities', subcategory: 'Electric' },
  ameren: { category: 'Utilities', subcategory: 'Electric' },
  evergy: { category: 'Utilities', subcategory: 'Electric' },
  eversource: { category: 'Utilities', subcategory: 'Electric' },
  'dte energy': { category: 'Utilities', subcategory: 'Electric' },
  'consumers energy': { category: 'Utilities', subcategory: 'Electric' },
  'ppl electric': { category: 'Utilities', subcategory: 'Electric' },

  // ─── Water Utilities ─────────────────────────────────────────────────
  'american water': { category: 'Utilities', subcategory: 'Water' },
  'water utility': { category: 'Utilities', subcategory: 'Water' },

  // ─── Health & Medical ────────────────────────────────────────────────
  cvs: { category: 'Health & Medical', subcategory: 'Pharmacy' },
  'cvs pharmacy': { category: 'Health & Medical', subcategory: 'Pharmacy' },
  walgreens: { category: 'Health & Medical', subcategory: 'Pharmacy' },
  'rite aid': { category: 'Health & Medical', subcategory: 'Pharmacy' },
  'express scripts': { category: 'Health & Medical', subcategory: 'Pharmacy' },
  caremark: { category: 'Health & Medical', subcategory: 'Pharmacy' },
  optumrx: { category: 'Health & Medical', subcategory: 'Pharmacy' },
  'capsule pharmacy': { category: 'Health & Medical', subcategory: 'Pharmacy' },
  'costco pharmacy': { category: 'Health & Medical', subcategory: 'Pharmacy' },
  'walmart pharmacy': { category: 'Health & Medical', subcategory: 'Pharmacy' },
  'kaiser permanente': { category: 'Health & Medical', subcategory: 'Doctor' },
  unitedhealth: { category: 'Health & Medical', subcategory: 'Health Insurance' },
  'united healthcare': { category: 'Health & Medical', subcategory: 'Health Insurance' },
  anthem: { category: 'Health & Medical', subcategory: 'Health Insurance' },
  'blue cross': { category: 'Health & Medical', subcategory: 'Health Insurance' },
  'blue shield': { category: 'Health & Medical', subcategory: 'Health Insurance' },
  cigna: { category: 'Health & Medical', subcategory: 'Health Insurance' },
  aetna: { category: 'Health & Medical', subcategory: 'Health Insurance' },
  humana: { category: 'Health & Medical', subcategory: 'Health Insurance' },
  molina: { category: 'Health & Medical', subcategory: 'Health Insurance' },
  'oscar health': { category: 'Health & Medical', subcategory: 'Health Insurance' },
  lenscrafters: { category: 'Health & Medical', subcategory: 'Vision' },
  'warby parker': { category: 'Health & Medical', subcategory: 'Vision' },
  'pearle vision': { category: 'Health & Medical', subcategory: 'Vision' },
  visionworks: { category: 'Health & Medical', subcategory: 'Vision' },
  '1-800 contacts': { category: 'Health & Medical', subcategory: 'Vision' },
  'aspen dental': { category: 'Health & Medical', subcategory: 'Dental' },
  'heartland dental': { category: 'Health & Medical', subcategory: 'Dental' },

  // ─── Fitness ─────────────────────────────────────────────────────────
  'planet fitness': { category: 'Health & Medical', subcategory: 'Gym & Fitness' },
  'la fitness': { category: 'Health & Medical', subcategory: 'Gym & Fitness' },
  equinox: { category: 'Health & Medical', subcategory: 'Gym & Fitness' },
  'anytime fitness': { category: 'Health & Medical', subcategory: 'Gym & Fitness' },
  orangetheory: { category: 'Health & Medical', subcategory: 'Gym & Fitness' },
  'orange theory': { category: 'Health & Medical', subcategory: 'Gym & Fitness' },
  crossfit: { category: 'Health & Medical', subcategory: 'Gym & Fitness' },
  ymca: { category: 'Health & Medical', subcategory: 'Gym & Fitness' },
  "gold's gym": { category: 'Health & Medical', subcategory: 'Gym & Fitness' },
  'golds gym': { category: 'Health & Medical', subcategory: 'Gym & Fitness' },
  'crunch fitness': { category: 'Health & Medical', subcategory: 'Gym & Fitness' },
  'lifetime fitness': { category: 'Health & Medical', subcategory: 'Gym & Fitness' },
  'life time': { category: 'Health & Medical', subcategory: 'Gym & Fitness' },
  '24 hour fitness': { category: 'Health & Medical', subcategory: 'Gym & Fitness' },
  peloton: { category: 'Health & Medical', subcategory: 'Gym & Fitness' },
  soulcycle: { category: 'Health & Medical', subcategory: 'Gym & Fitness' },
  "barry's bootcamp": { category: 'Health & Medical', subcategory: 'Gym & Fitness' },
  f45: { category: 'Health & Medical', subcategory: 'Gym & Fitness' },
  classpass: { category: 'Health & Medical', subcategory: 'Gym & Fitness' },

  // ─── Software / SaaS ────────────────────────────────────────────────
  google: { category: 'Shopping', subcategory: 'Online Shopping' },
  'google storage': { category: 'Shopping', subcategory: 'Online Shopping' },
  'google one': { category: 'Shopping', subcategory: 'Online Shopping' },
  icloud: { category: 'Shopping', subcategory: 'Online Shopping' },
  'apple icloud': { category: 'Shopping', subcategory: 'Online Shopping' },
  'microsoft 365': { category: 'Shopping', subcategory: 'Online Shopping' },
  'microsoft office': { category: 'Shopping', subcategory: 'Online Shopping' },
  adobe: { category: 'Shopping', subcategory: 'Online Shopping' },
  'adobe creative cloud': { category: 'Shopping', subcategory: 'Online Shopping' },
  dropbox: { category: 'Shopping', subcategory: 'Online Shopping' },
  zoom: { category: 'Shopping', subcategory: 'Online Shopping' },
  slack: { category: 'Shopping', subcategory: 'Online Shopping' },
  notion: { category: 'Shopping', subcategory: 'Online Shopping' },
  canva: { category: 'Shopping', subcategory: 'Online Shopping' },
  grammarly: { category: 'Shopping', subcategory: 'Online Shopping' },
  chatgpt: { category: 'Shopping', subcategory: 'Online Shopping' },
  openai: { category: 'Shopping', subcategory: 'Online Shopping' },
  github: { category: 'Shopping', subcategory: 'Online Shopping' },
  figma: { category: 'Shopping', subcategory: 'Online Shopping' },
  squarespace: { category: 'Shopping', subcategory: 'Online Shopping' },
  wix: { category: 'Shopping', subcategory: 'Online Shopping' },
  godaddy: { category: 'Shopping', subcategory: 'Online Shopping' },
  namecheap: { category: 'Shopping', subcategory: 'Online Shopping' },
  wordpress: { category: 'Shopping', subcategory: 'Online Shopping' },
  mailchimp: { category: 'Shopping', subcategory: 'Online Shopping' },
  quickbooks: { category: 'Shopping', subcategory: 'Online Shopping' },
  intuit: { category: 'Shopping', subcategory: 'Online Shopping' },
  turbotax: { category: 'Financial', subcategory: 'Taxes' },
  'h&r block': { category: 'Financial', subcategory: 'Taxes' },
  hrblock: { category: 'Financial', subcategory: 'Taxes' },
  norton: { category: 'Shopping', subcategory: 'Online Shopping' },
  mcafee: { category: 'Shopping', subcategory: 'Online Shopping' },
  nordvpn: { category: 'Shopping', subcategory: 'Online Shopping' },
  expressvpn: { category: 'Shopping', subcategory: 'Online Shopping' },
  lastpass: { category: 'Shopping', subcategory: 'Online Shopping' },
  '1password': { category: 'Shopping', subcategory: 'Online Shopping' },
  dashlane: { category: 'Shopping', subcategory: 'Online Shopping' },
  evernote: { category: 'Shopping', subcategory: 'Online Shopping' },
  todoist: { category: 'Shopping', subcategory: 'Online Shopping' },
  headspace: { category: 'Health & Medical', subcategory: 'Gym & Fitness' },
  calm: { category: 'Health & Medical', subcategory: 'Gym & Fitness' },

  // ─── Online Marketplaces ─────────────────────────────────────────────
  ebay: { category: 'Shopping', subcategory: 'Online Shopping' },
  etsy: { category: 'Shopping', subcategory: 'Online Shopping' },
  wish: { category: 'Shopping', subcategory: 'Online Shopping' },
  aliexpress: { category: 'Shopping', subcategory: 'Online Shopping' },
  temu: { category: 'Shopping', subcategory: 'Online Shopping' },
  mercari: { category: 'Shopping', subcategory: 'Online Shopping' },
  poshmark: { category: 'Shopping', subcategory: 'Online Shopping' },
  depop: { category: 'Shopping', subcategory: 'Online Shopping' },
  offerup: { category: 'Shopping', subcategory: 'Online Shopping' },
  'facebook marketplace': { category: 'Shopping', subcategory: 'Online Shopping' },
  shopify: { category: 'Shopping', subcategory: 'Online Shopping' },

  // ─── Sporting Goods ──────────────────────────────────────────────────
  'dicks sporting goods': { category: 'Shopping', subcategory: 'Sporting Goods' },
  "dick's sporting goods": { category: 'Shopping', subcategory: 'Sporting Goods' },
  'academy sports': { category: 'Shopping', subcategory: 'Sporting Goods' },
  rei: { category: 'Shopping', subcategory: 'Sporting Goods' },
  'bass pro shops': { category: 'Shopping', subcategory: 'Sporting Goods' },
  cabelas: { category: 'Shopping', subcategory: 'Sporting Goods' },
  "cabela's": { category: 'Shopping', subcategory: 'Sporting Goods' },

  // ─── Travel - Flights ────────────────────────────────────────────────
  'delta airlines': { category: 'Travel', subcategory: 'Flights' },
  'delta air lines': { category: 'Travel', subcategory: 'Flights' },
  'american airlines': { category: 'Travel', subcategory: 'Flights' },
  'united airlines': { category: 'Travel', subcategory: 'Flights' },
  'southwest airlines': { category: 'Travel', subcategory: 'Flights' },
  jetblue: { category: 'Travel', subcategory: 'Flights' },
  'spirit airlines': { category: 'Travel', subcategory: 'Flights' },
  'frontier airlines': { category: 'Travel', subcategory: 'Flights' },
  'alaska airlines': { category: 'Travel', subcategory: 'Flights' },
  'hawaiian airlines': { category: 'Travel', subcategory: 'Flights' },
  'sun country': { category: 'Travel', subcategory: 'Flights' },
  'allegiant air': { category: 'Travel', subcategory: 'Flights' },
  'air canada': { category: 'Travel', subcategory: 'Flights' },
  'british airways': { category: 'Travel', subcategory: 'Flights' },
  lufthansa: { category: 'Travel', subcategory: 'Flights' },
  emirates: { category: 'Travel', subcategory: 'Flights' },
  'qatar airways': { category: 'Travel', subcategory: 'Flights' },
  'turkish airlines': { category: 'Travel', subcategory: 'Flights' },
  'ryan air': { category: 'Travel', subcategory: 'Flights' },
  ryanair: { category: 'Travel', subcategory: 'Flights' },
  easyjet: { category: 'Travel', subcategory: 'Flights' },
  expedia: { category: 'Travel', subcategory: 'Flights' },
  kayak: { category: 'Travel', subcategory: 'Flights' },
  skyscanner: { category: 'Travel', subcategory: 'Flights' },
  'google flights': { category: 'Travel', subcategory: 'Flights' },
  hopper: { category: 'Travel', subcategory: 'Flights' },

  // ─── Travel - Hotels ─────────────────────────────────────────────────
  marriott: { category: 'Travel', subcategory: 'Hotels' },
  hilton: { category: 'Travel', subcategory: 'Hotels' },
  hyatt: { category: 'Travel', subcategory: 'Hotels' },
  ihg: { category: 'Travel', subcategory: 'Hotels' },
  intercontinental: { category: 'Travel', subcategory: 'Hotels' },
  'holiday inn': { category: 'Travel', subcategory: 'Hotels' },
  'best western': { category: 'Travel', subcategory: 'Hotels' },
  wyndham: { category: 'Travel', subcategory: 'Hotels' },
  'choice hotels': { category: 'Travel', subcategory: 'Hotels' },
  radisson: { category: 'Travel', subcategory: 'Hotels' },
  'motel 6': { category: 'Travel', subcategory: 'Hotels' },
  'la quinta': { category: 'Travel', subcategory: 'Hotels' },
  'hampton inn': { category: 'Travel', subcategory: 'Hotels' },
  'courtyard by marriott': { category: 'Travel', subcategory: 'Hotels' },
  airbnb: { category: 'Travel', subcategory: 'Hotels' },
  vrbo: { category: 'Travel', subcategory: 'Hotels' },
  'booking.com': { category: 'Travel', subcategory: 'Hotels' },
  'hotels.com': { category: 'Travel', subcategory: 'Hotels' },
  trivago: { category: 'Travel', subcategory: 'Hotels' },
  hostelworld: { category: 'Travel', subcategory: 'Hotels' },

  // ─── Travel - Car Rental ─────────────────────────────────────────────
  hertz: { category: 'Travel', subcategory: 'Car Rental' },
  enterprise: { category: 'Travel', subcategory: 'Car Rental' },
  'enterprise rent-a-car': { category: 'Travel', subcategory: 'Car Rental' },
  avis: { category: 'Travel', subcategory: 'Car Rental' },
  'budget car rental': { category: 'Travel', subcategory: 'Car Rental' },
  'national car rental': { category: 'Travel', subcategory: 'Car Rental' },
  alamo: { category: 'Travel', subcategory: 'Car Rental' },
  'dollar car rental': { category: 'Travel', subcategory: 'Car Rental' },
  'thrifty car rental': { category: 'Travel', subcategory: 'Car Rental' },
  sixt: { category: 'Travel', subcategory: 'Car Rental' },
  turo: { category: 'Travel', subcategory: 'Car Rental' },
  zipcar: { category: 'Travel', subcategory: 'Car Rental' },

  // ─── Education ───────────────────────────────────────────────────────
  coursera: { category: 'Education', subcategory: 'Tuition' },
  udemy: { category: 'Education', subcategory: 'Tuition' },
  skillshare: { category: 'Education', subcategory: 'Tuition' },
  masterclass: { category: 'Education', subcategory: 'Tuition' },
  'linkedin learning': { category: 'Education', subcategory: 'Tuition' },
  duolingo: { category: 'Education', subcategory: 'Books & Supplies' },
  'khan academy': { category: 'Education', subcategory: 'Tuition' },
  chegg: { category: 'Education', subcategory: 'Books & Supplies' },
  'barnes and noble': { category: 'Education', subcategory: 'Books & Supplies' },
  'barnes & noble': { category: 'Education', subcategory: 'Books & Supplies' },
  'half price books': { category: 'Education', subcategory: 'Books & Supplies' },
  'amazon kindle': { category: 'Entertainment', subcategory: 'Books' },
  'kindle unlimited': { category: 'Entertainment', subcategory: 'Books' },
  scribd: { category: 'Entertainment', subcategory: 'Books' },

  // ─── Personal Care ───────────────────────────────────────────────────
  supercuts: { category: 'Personal Care', subcategory: 'Hair' },
  'great clips': { category: 'Personal Care', subcategory: 'Hair' },
  'sport clips': { category: 'Personal Care', subcategory: 'Hair' },
  'fantastic sams': { category: 'Personal Care', subcategory: 'Hair' },
  "floyd's 99": { category: 'Personal Care', subcategory: 'Hair' },
  ulta: { category: 'Personal Care', subcategory: 'Spa & Beauty' },
  'ulta beauty': { category: 'Personal Care', subcategory: 'Spa & Beauty' },
  sephora: { category: 'Personal Care', subcategory: 'Spa & Beauty' },
  'sally beauty': { category: 'Personal Care', subcategory: 'Spa & Beauty' },
  'massage envy': { category: 'Personal Care', subcategory: 'Spa & Beauty' },
  'european wax center': { category: 'Personal Care', subcategory: 'Spa & Beauty' },
  'hand and stone': { category: 'Personal Care', subcategory: 'Spa & Beauty' },
  drybar: { category: 'Personal Care', subcategory: 'Hair' },
  'madison reed': { category: 'Personal Care', subcategory: 'Hair' },

  // ─── Pets ────────────────────────────────────────────────────────────
  petco: { category: 'Pets', subcategory: 'Pet Supplies' },
  petsmart: { category: 'Pets', subcategory: 'Pet Supplies' },
  chewy: { category: 'Pets', subcategory: 'Pet Food' },
  'chewy.com': { category: 'Pets', subcategory: 'Pet Food' },
  banfield: { category: 'Pets', subcategory: 'Vet' },
  'banfield pet hospital': { category: 'Pets', subcategory: 'Vet' },
  vetco: { category: 'Pets', subcategory: 'Vet' },
  'vca animal hospital': { category: 'Pets', subcategory: 'Vet' },
  rover: { category: 'Pets', subcategory: 'Pet Supplies' },
  'rover.com': { category: 'Pets', subcategory: 'Pet Supplies' },
  wag: { category: 'Pets', subcategory: 'Pet Supplies' },
  barkbox: { category: 'Pets', subcategory: 'Pet Supplies' },
  'bark box': { category: 'Pets', subcategory: 'Pet Supplies' },

  // ─── Gifts & Donations ──────────────────────────────────────────────
  'red cross': { category: 'Gifts & Donations', subcategory: 'Charity' },
  'salvation army': { category: 'Gifts & Donations', subcategory: 'Charity' },
  goodwill: { category: 'Gifts & Donations', subcategory: 'Charity' },
  'habitat for humanity': { category: 'Gifts & Donations', subcategory: 'Charity' },
  'united way': { category: 'Gifts & Donations', subcategory: 'Charity' },
  gofundme: { category: 'Gifts & Donations', subcategory: 'Charity' },
  'donors choose': { category: 'Gifts & Donations', subcategory: 'Charity' },
  'st. jude': { category: 'Gifts & Donations', subcategory: 'Charity' },
  hallmark: { category: 'Gifts & Donations', subcategory: 'Gifts' },

  // ─── Financial / Banking ─────────────────────────────────────────────
  venmo: { category: 'Transfers', subcategory: 'Account Transfer' },
  paypal: { category: 'Transfers', subcategory: 'Account Transfer' },
  zelle: { category: 'Transfers', subcategory: 'Account Transfer' },
  'cash app': { category: 'Transfers', subcategory: 'Account Transfer' },
  'square cash': { category: 'Transfers', subcategory: 'Account Transfer' },
  wise: { category: 'Transfers', subcategory: 'Account Transfer' },
  transferwise: { category: 'Transfers', subcategory: 'Account Transfer' },
  'western union': { category: 'Transfers', subcategory: 'Account Transfer' },
  moneygram: { category: 'Transfers', subcategory: 'Account Transfer' },
  chase: { category: 'Financial', subcategory: 'Bank Fees' },
  'bank of america': { category: 'Financial', subcategory: 'Bank Fees' },
  'wells fargo': { category: 'Financial', subcategory: 'Bank Fees' },
  citibank: { category: 'Financial', subcategory: 'Bank Fees' },
  'us bank': { category: 'Financial', subcategory: 'Bank Fees' },
  'capital one': { category: 'Financial', subcategory: 'Bank Fees' },
  'td bank': { category: 'Financial', subcategory: 'Bank Fees' },
  'pnc bank': { category: 'Financial', subcategory: 'Bank Fees' },
  truist: { category: 'Financial', subcategory: 'Bank Fees' },
  'fifth third bank': { category: 'Financial', subcategory: 'Bank Fees' },
  'regions bank': { category: 'Financial', subcategory: 'Bank Fees' },
  'huntington bank': { category: 'Financial', subcategory: 'Bank Fees' },
  'key bank': { category: 'Financial', subcategory: 'Bank Fees' },
  'citizens bank': { category: 'Financial', subcategory: 'Bank Fees' },
  'm&t bank': { category: 'Financial', subcategory: 'Bank Fees' },
  'ally bank': { category: 'Financial', subcategory: 'Bank Fees' },
  'discover bank': { category: 'Financial', subcategory: 'Bank Fees' },
  marcus: { category: 'Financial', subcategory: 'Bank Fees' },
  sofi: { category: 'Financial', subcategory: 'Bank Fees' },
  chime: { category: 'Financial', subcategory: 'Bank Fees' },
  robinhood: { category: 'Transfers', subcategory: 'Investment Transfer' },
  fidelity: { category: 'Transfers', subcategory: 'Investment Transfer' },
  vanguard: { category: 'Transfers', subcategory: 'Investment Transfer' },
  'charles schwab': { category: 'Transfers', subcategory: 'Investment Transfer' },
  schwab: { category: 'Transfers', subcategory: 'Investment Transfer' },
  'td ameritrade': { category: 'Transfers', subcategory: 'Investment Transfer' },
  'e*trade': { category: 'Transfers', subcategory: 'Investment Transfer' },
  etrade: { category: 'Transfers', subcategory: 'Investment Transfer' },
  'merrill lynch': { category: 'Transfers', subcategory: 'Investment Transfer' },
  merrill: { category: 'Transfers', subcategory: 'Investment Transfer' },
  wealthfront: { category: 'Transfers', subcategory: 'Investment Transfer' },
  betterment: { category: 'Transfers', subcategory: 'Investment Transfer' },
  acorns: { category: 'Transfers', subcategory: 'Investment Transfer' },
  coinbase: { category: 'Transfers', subcategory: 'Investment Transfer' },
  binance: { category: 'Transfers', subcategory: 'Investment Transfer' },
  kraken: { category: 'Transfers', subcategory: 'Investment Transfer' },

  // ─── Insurance (non-auto) ────────────────────────────────────────────
  metlife: { category: 'Financial', subcategory: 'Insurance' },
  prudential: { category: 'Financial', subcategory: 'Insurance' },
  'new york life': { category: 'Financial', subcategory: 'Insurance' },
  'northwestern mutual': { category: 'Financial', subcategory: 'Insurance' },
  aflac: { category: 'Financial', subcategory: 'Insurance' },
  lemonade: { category: 'Financial', subcategory: 'Insurance' },
  travelers: { category: 'Financial', subcategory: 'Insurance' },
  hartford: { category: 'Financial', subcategory: 'Insurance' },
  'the hartford': { category: 'Financial', subcategory: 'Insurance' },

  // ─── Convenience Stores ──────────────────────────────────────────────
  '7-eleven': { category: 'Food & Drink', subcategory: 'Groceries' },
  '7 eleven': { category: 'Food & Drink', subcategory: 'Groceries' },

  // ─── Subscription Boxes ──────────────────────────────────────────────
  birchbox: { category: 'Personal Care', subcategory: 'Spa & Beauty' },
  ipsy: { category: 'Personal Care', subcategory: 'Spa & Beauty' },
  fabfitfun: { category: 'Personal Care', subcategory: 'Spa & Beauty' },
  'dollar shave club': { category: 'Personal Care', subcategory: 'Spa & Beauty' },
  "harry's": { category: 'Personal Care', subcategory: 'Spa & Beauty' },
  harrys: { category: 'Personal Care', subcategory: 'Spa & Beauty' },

  // ─── Office Supplies ─────────────────────────────────────────────────
  staples: { category: 'Shopping', subcategory: 'Home Goods' },
  'office depot': { category: 'Shopping', subcategory: 'Home Goods' },
  officedepot: { category: 'Shopping', subcategory: 'Home Goods' },

  // ─── Childcare & Kids ────────────────────────────────────────────────
  kindercare: { category: 'Education', subcategory: 'Tuition' },
  'bright horizons': { category: 'Education', subcategory: 'Tuition' },
  kumon: { category: 'Education', subcategory: 'Tuition' },
  mathnasium: { category: 'Education', subcategory: 'Tuition' },
  'sylvan learning': { category: 'Education', subcategory: 'Tuition' },

  // ─── Laundry / Dry Cleaning ──────────────────────────────────────────
  'tide cleaners': { category: 'Personal Care', subcategory: 'Laundry' },
  martinizing: { category: 'Personal Care', subcategory: 'Laundry' },
  'zips dry cleaners': { category: 'Personal Care', subcategory: 'Laundry' },
};

/**
 * MCC (Merchant Category Code) to category mapping.
 * MCCs are 4-digit codes assigned by card networks to classify merchants.
 */
export const MCC_DATABASE: Record<string, MerchantEntry> = {
  // Airlines
  '3000': { category: 'Travel', subcategory: 'Flights' },
  '3001': { category: 'Travel', subcategory: 'Flights' },
  '3002': { category: 'Travel', subcategory: 'Flights' },
  '3003': { category: 'Travel', subcategory: 'Flights' },
  '4511': { category: 'Travel', subcategory: 'Flights' },

  // Car Rental
  '3351': { category: 'Travel', subcategory: 'Car Rental' },
  '3352': { category: 'Travel', subcategory: 'Car Rental' },
  '3353': { category: 'Travel', subcategory: 'Car Rental' },
  '3354': { category: 'Travel', subcategory: 'Car Rental' },
  '3355': { category: 'Travel', subcategory: 'Car Rental' },
  '3357': { category: 'Travel', subcategory: 'Car Rental' },
  '3359': { category: 'Travel', subcategory: 'Car Rental' },
  '3366': { category: 'Travel', subcategory: 'Car Rental' },
  '3381': { category: 'Travel', subcategory: 'Car Rental' },
  '7512': { category: 'Travel', subcategory: 'Car Rental' },

  // Hotels / Lodging
  '3501': { category: 'Travel', subcategory: 'Hotels' },
  '3502': { category: 'Travel', subcategory: 'Hotels' },
  '3503': { category: 'Travel', subcategory: 'Hotels' },
  '3504': { category: 'Travel', subcategory: 'Hotels' },
  '7011': { category: 'Travel', subcategory: 'Hotels' },

  // Restaurants
  '5811': { category: 'Food & Drink', subcategory: 'Restaurants' },
  '5812': { category: 'Food & Drink', subcategory: 'Restaurants' },

  // Fast Food
  '5814': { category: 'Food & Drink', subcategory: 'Fast Food' },

  // Bars / Drinking Places
  '5813': { category: 'Food & Drink', subcategory: 'Bars & Alcohol' },

  // Grocery Stores
  '5411': { category: 'Food & Drink', subcategory: 'Groceries' },
  '5422': { category: 'Food & Drink', subcategory: 'Groceries' },
  '5441': { category: 'Food & Drink', subcategory: 'Groceries' },
  '5451': { category: 'Food & Drink', subcategory: 'Groceries' },
  '5462': { category: 'Food & Drink', subcategory: 'Groceries' },
  '5499': { category: 'Food & Drink', subcategory: 'Groceries' },

  // Gas Stations
  '5541': { category: 'Transportation', subcategory: 'Gas & Fuel' },
  '5542': { category: 'Transportation', subcategory: 'Gas & Fuel' },

  // Auto Repair / Service
  '7531': { category: 'Transportation', subcategory: 'Auto Maintenance' },
  '7534': { category: 'Transportation', subcategory: 'Auto Maintenance' },
  '7535': { category: 'Transportation', subcategory: 'Auto Maintenance' },
  '7538': { category: 'Transportation', subcategory: 'Auto Maintenance' },
  '7542': { category: 'Transportation', subcategory: 'Auto Maintenance' },
  '5511': { category: 'Transportation', subcategory: 'Auto Maintenance' },
  '5521': { category: 'Transportation', subcategory: 'Auto Maintenance' },
  '5531': { category: 'Transportation', subcategory: 'Auto Maintenance' },
  '5532': { category: 'Transportation', subcategory: 'Auto Maintenance' },
  '5533': { category: 'Transportation', subcategory: 'Auto Maintenance' },

  // Parking
  '7523': { category: 'Transportation', subcategory: 'Parking' },

  // Public Transit
  '4111': { category: 'Transportation', subcategory: 'Public Transit' },
  '4112': { category: 'Transportation', subcategory: 'Public Transit' },
  '4121': { category: 'Transportation', subcategory: 'Ride Share' },
  '4131': { category: 'Transportation', subcategory: 'Public Transit' },

  // Department Stores
  '5311': { category: 'Shopping', subcategory: 'Home Goods' },

  // Clothing / Apparel
  '5611': { category: 'Shopping', subcategory: 'Clothing' },
  '5621': { category: 'Shopping', subcategory: 'Clothing' },
  '5631': { category: 'Shopping', subcategory: 'Clothing' },
  '5641': { category: 'Shopping', subcategory: 'Clothing' },
  '5651': { category: 'Shopping', subcategory: 'Clothing' },
  '5661': { category: 'Shopping', subcategory: 'Clothing' },
  '5681': { category: 'Shopping', subcategory: 'Clothing' },
  '5691': { category: 'Shopping', subcategory: 'Clothing' },
  '5699': { category: 'Shopping', subcategory: 'Clothing' },

  // Electronics
  '5732': { category: 'Shopping', subcategory: 'Electronics' },
  '5734': { category: 'Shopping', subcategory: 'Electronics' },
  '5735': { category: 'Shopping', subcategory: 'Electronics' },
  '5045': { category: 'Shopping', subcategory: 'Electronics' },
  '5946': { category: 'Shopping', subcategory: 'Electronics' },

  // Sporting Goods
  '5941': { category: 'Shopping', subcategory: 'Sporting Goods' },

  // Home Improvement / Hardware
  '5200': { category: 'Housing', subcategory: 'Home Improvement' },
  '5211': { category: 'Housing', subcategory: 'Home Improvement' },
  '5231': { category: 'Housing', subcategory: 'Home Improvement' },
  '5251': { category: 'Housing', subcategory: 'Home Improvement' },
  '5261': { category: 'Housing', subcategory: 'Home Improvement' },

  // Furniture / Home Goods
  '5712': { category: 'Shopping', subcategory: 'Home Goods' },
  '5713': { category: 'Shopping', subcategory: 'Home Goods' },
  '5714': { category: 'Shopping', subcategory: 'Home Goods' },
  '5719': { category: 'Shopping', subcategory: 'Home Goods' },

  // Drug Stores / Pharmacies
  '5912': { category: 'Health & Medical', subcategory: 'Pharmacy' },

  // Medical
  '8011': { category: 'Health & Medical', subcategory: 'Doctor' },
  '8021': { category: 'Health & Medical', subcategory: 'Dental' },
  '8031': { category: 'Health & Medical', subcategory: 'Doctor' },
  '8041': { category: 'Health & Medical', subcategory: 'Doctor' },
  '8042': { category: 'Health & Medical', subcategory: 'Vision' },
  '8043': { category: 'Health & Medical', subcategory: 'Vision' },
  '8049': { category: 'Health & Medical', subcategory: 'Doctor' },
  '8050': { category: 'Health & Medical', subcategory: 'Doctor' },
  '8062': { category: 'Health & Medical', subcategory: 'Doctor' },
  '8071': { category: 'Health & Medical', subcategory: 'Doctor' },
  '8099': { category: 'Health & Medical', subcategory: 'Doctor' },

  // Veterinary
  '0742': { category: 'Pets', subcategory: 'Vet' },

  // Health / Fitness
  '7941': { category: 'Health & Medical', subcategory: 'Gym & Fitness' },
  '7911': { category: 'Health & Medical', subcategory: 'Gym & Fitness' },
  '7997': { category: 'Health & Medical', subcategory: 'Gym & Fitness' },

  // Entertainment
  '7832': { category: 'Entertainment', subcategory: 'Movies & Theater' },
  '7829': { category: 'Entertainment', subcategory: 'Movies & Theater' },
  '7922': { category: 'Entertainment', subcategory: 'Movies & Theater' },
  '7841': { category: 'Entertainment', subcategory: 'Streaming Services' },
  '7993': { category: 'Entertainment', subcategory: 'Games' },
  '7994': { category: 'Entertainment', subcategory: 'Games' },
  '7996': { category: 'Entertainment', subcategory: 'Hobbies' },
  '5942': { category: 'Entertainment', subcategory: 'Books' },
  '5943': { category: 'Entertainment', subcategory: 'Books' },

  // Education
  '8211': { category: 'Education', subcategory: 'Tuition' },
  '8220': { category: 'Education', subcategory: 'Tuition' },
  '8241': { category: 'Education', subcategory: 'Tuition' },
  '8244': { category: 'Education', subcategory: 'Tuition' },
  '8249': { category: 'Education', subcategory: 'Tuition' },
  '8299': { category: 'Education', subcategory: 'Tuition' },

  // Utilities
  '4812': { category: 'Utilities', subcategory: 'Phone' },
  '4813': { category: 'Utilities', subcategory: 'Phone' },
  '4814': { category: 'Utilities', subcategory: 'Phone' },
  '4815': { category: 'Utilities', subcategory: 'Phone' },
  '4816': { category: 'Utilities', subcategory: 'Internet' },
  '4821': { category: 'Utilities', subcategory: 'Phone' },
  '4899': { category: 'Utilities', subcategory: 'Internet' },
  '4900': { category: 'Utilities', subcategory: 'Electric' },

  // Insurance
  '6300': { category: 'Financial', subcategory: 'Insurance' },
  '5960': { category: 'Financial', subcategory: 'Insurance' },

  // Personal Care
  '7230': { category: 'Personal Care', subcategory: 'Hair' },
  '7297': { category: 'Personal Care', subcategory: 'Spa & Beauty' },
  '7298': { category: 'Personal Care', subcategory: 'Spa & Beauty' },

  // Laundry
  '7210': { category: 'Personal Care', subcategory: 'Laundry' },
  '7211': { category: 'Personal Care', subcategory: 'Laundry' },
  '7216': { category: 'Personal Care', subcategory: 'Laundry' },

  // Charities / Donations
  '8398': { category: 'Gifts & Donations', subcategory: 'Charity' },
  '8641': { category: 'Gifts & Donations', subcategory: 'Charity' },

  // Pet Stores
  '5995': { category: 'Pets', subcategory: 'Pet Supplies' },

  // Gifts / Flowers / Cards
  '5947': { category: 'Gifts & Donations', subcategory: 'Gifts' },

  // Taxes / Government
  '9211': { category: 'Financial', subcategory: 'Taxes' },
  '9222': { category: 'Financial', subcategory: 'Taxes' },
  '9311': { category: 'Financial', subcategory: 'Taxes' },
  '9399': { category: 'Financial', subcategory: 'Taxes' },
  '9402': { category: 'Financial', subcategory: 'Taxes' },
};

/**
 * Keyword-based fallback matching. Checked when no exact merchant match is found.
 * Order matters: more specific keywords should appear first.
 */
export const KEYWORD_RULES: Array<{
  keywords: string[];
  category: string;
  subcategory: string;
}> = [
  // Streaming / Subscriptions
  {
    keywords: ['streaming', 'stream'],
    category: 'Entertainment',
    subcategory: 'Streaming Services',
  },

  // Gas & Fuel
  {
    keywords: ['gas station', 'fuel', 'petroleum', 'gasoline', 'diesel'],
    category: 'Transportation',
    subcategory: 'Gas & Fuel',
  },
  { keywords: ['oil change', 'lube'], category: 'Transportation', subcategory: 'Auto Maintenance' },
  {
    keywords: ['car wash', 'auto wash'],
    category: 'Transportation',
    subcategory: 'Auto Maintenance',
  },
  { keywords: ['tire', 'tyre'], category: 'Transportation', subcategory: 'Auto Maintenance' },
  {
    keywords: ['towing', 'tow service'],
    category: 'Transportation',
    subcategory: 'Auto Maintenance',
  },
  {
    keywords: ['parking', 'park garage', 'park lot'],
    category: 'Transportation',
    subcategory: 'Parking',
  },
  {
    keywords: ['toll', 'e-zpass', 'ez pass', 'ipass', 'sunpass'],
    category: 'Transportation',
    subcategory: 'Gas & Fuel',
  },

  // Ride Share / Transit
  {
    keywords: ['taxi', 'cab', 'rideshare', 'ride share'],
    category: 'Transportation',
    subcategory: 'Ride Share',
  },
  {
    keywords: ['transit', 'subway', 'bus pass', 'train'],
    category: 'Transportation',
    subcategory: 'Public Transit',
  },

  // Food
  {
    keywords: ['coffee', 'cafe', 'espresso', 'latte'],
    category: 'Food & Drink',
    subcategory: 'Coffee Shops',
  },
  {
    keywords: ['pizza', 'burger', 'taco', 'chicken', 'wing', 'sub shop', 'sandwich'],
    category: 'Food & Drink',
    subcategory: 'Fast Food',
  },
  {
    keywords: [
      'restaurant',
      'grill',
      'bistro',
      'diner',
      'eatery',
      'trattoria',
      'sushi',
      'steakhouse',
      'brasserie',
      'tavern',
    ],
    category: 'Food & Drink',
    subcategory: 'Restaurants',
  },
  {
    keywords: ['grocery', 'supermarket', 'food market', 'farmers market', 'produce'],
    category: 'Food & Drink',
    subcategory: 'Groceries',
  },
  {
    keywords: ['bakery', 'bread', 'donut', 'doughnut', 'pastry'],
    category: 'Food & Drink',
    subcategory: 'Groceries',
  },
  {
    keywords: ['bar ', 'pub ', 'brewery', 'taproom', 'wine bar', 'liquor', 'spirits'],
    category: 'Food & Drink',
    subcategory: 'Bars & Alcohol',
  },

  // Shopping
  {
    keywords: ['electronics', 'computer', 'phone store', 'cell phone'],
    category: 'Shopping',
    subcategory: 'Electronics',
  },
  {
    keywords: ['clothing', 'apparel', 'fashion', 'boutique', 'shoes', 'shoe store'],
    category: 'Shopping',
    subcategory: 'Clothing',
  },
  {
    keywords: ['furniture', 'mattress', 'home decor'],
    category: 'Shopping',
    subcategory: 'Home Goods',
  },
  {
    keywords: ['sporting goods', 'sports store', 'outdoor gear'],
    category: 'Shopping',
    subcategory: 'Sporting Goods',
  },

  // Housing
  { keywords: ['rent', 'lease payment', 'apartment'], category: 'Housing', subcategory: 'Rent' },
  { keywords: ['mortgage'], category: 'Housing', subcategory: 'Mortgage' },
  { keywords: ['property tax'], category: 'Housing', subcategory: 'Property Tax' },
  {
    keywords: ['hardware', 'lumber', 'plumbing', 'paint store'],
    category: 'Housing',
    subcategory: 'Home Improvement',
  },

  // Utilities
  {
    keywords: ['electric', 'power company', 'energy company'],
    category: 'Utilities',
    subcategory: 'Electric',
  },
  {
    keywords: ['water utility', 'water bill', 'sewer'],
    category: 'Utilities',
    subcategory: 'Water',
  },
  { keywords: ['internet', 'broadband', 'fiber'], category: 'Utilities', subcategory: 'Internet' },
  {
    keywords: ['phone bill', 'wireless', 'cellular', 'mobile plan'],
    category: 'Utilities',
    subcategory: 'Phone',
  },

  // Medical / Health
  {
    keywords: ['pharmacy', 'drug store', 'rx', 'prescription'],
    category: 'Health & Medical',
    subcategory: 'Pharmacy',
  },
  {
    keywords: [
      'doctor',
      'physician',
      'medical center',
      'clinic',
      'hospital',
      'urgent care',
      'health center',
    ],
    category: 'Health & Medical',
    subcategory: 'Doctor',
  },
  {
    keywords: ['dental', 'dentist', 'orthodonti'],
    category: 'Health & Medical',
    subcategory: 'Dental',
  },
  {
    keywords: [
      'vision',
      'optometrist',
      'eye doctor',
      'eye care',
      'optical',
      'eyeglasses',
      'contacts',
    ],
    category: 'Health & Medical',
    subcategory: 'Vision',
  },
  {
    keywords: ['gym', 'fitness', 'workout', 'yoga', 'pilates', 'crossfit'],
    category: 'Health & Medical',
    subcategory: 'Gym & Fitness',
  },
  {
    keywords: ['health insurance', 'medical insurance'],
    category: 'Health & Medical',
    subcategory: 'Health Insurance',
  },

  // Entertainment
  {
    keywords: ['cinema', 'movie', 'theater', 'theatre'],
    category: 'Entertainment',
    subcategory: 'Movies & Theater',
  },
  {
    keywords: ['concert', 'live music', 'ticketmaster', 'stubhub', 'eventbrite', 'livenation'],
    category: 'Entertainment',
    subcategory: 'Hobbies',
  },
  {
    keywords: ['museum', 'zoo', 'aquarium', 'amusement', 'theme park', 'water park'],
    category: 'Entertainment',
    subcategory: 'Hobbies',
  },
  {
    keywords: ['bookstore', 'book store', 'library'],
    category: 'Entertainment',
    subcategory: 'Books',
  },
  { keywords: ['game', 'gaming'], category: 'Entertainment', subcategory: 'Games' },

  // Education
  {
    keywords: ['university', 'college', 'school', 'tuition'],
    category: 'Education',
    subcategory: 'Tuition',
  },
  {
    keywords: ['student loan', 'sallie mae', 'navient', 'mohela', 'nelnet'],
    category: 'Education',
    subcategory: 'Student Loans',
  },

  // Travel (before Personal Care so "resort" matches before "spa")
  {
    keywords: ['airline', 'airways', 'air line', 'flight'],
    category: 'Travel',
    subcategory: 'Flights',
  },
  {
    keywords: ['hotel', 'motel', 'resort', 'lodge', 'hostel'],
    category: 'Travel',
    subcategory: 'Hotels',
  },
  {
    keywords: ['car rental', 'rental car', 'rent a car', 'rent-a-car'],
    category: 'Travel',
    subcategory: 'Car Rental',
  },

  // Personal Care
  {
    keywords: ['salon', 'barber', 'haircut', 'hair cut', 'hair studio'],
    category: 'Personal Care',
    subcategory: 'Hair',
  },
  {
    keywords: ['spa', 'massage', 'facial', 'beauty', 'nail', 'wax'],
    category: 'Personal Care',
    subcategory: 'Spa & Beauty',
  },
  {
    keywords: ['laundry', 'dry clean', 'cleaners'],
    category: 'Personal Care',
    subcategory: 'Laundry',
  },

  // Pets
  {
    keywords: ['veterinar', 'vet clinic', 'animal hospital', 'pet hospital'],
    category: 'Pets',
    subcategory: 'Vet',
  },
  {
    keywords: ['pet store', 'pet food', 'pet supply', 'pet shop'],
    category: 'Pets',
    subcategory: 'Pet Supplies',
  },

  // Financial
  { keywords: ['atm', 'cash withdrawal'], category: 'Financial', subcategory: 'ATM Fees' },
  {
    keywords: ['bank fee', 'service charge', 'monthly fee', 'overdraft'],
    category: 'Financial',
    subcategory: 'Bank Fees',
  },
  {
    keywords: ['interest charge', 'finance charge'],
    category: 'Financial',
    subcategory: 'Interest Charges',
  },
  {
    keywords: ['tax payment', 'irs', 'state tax', 'property tax'],
    category: 'Financial',
    subcategory: 'Taxes',
  },
  {
    keywords: [
      'insurance premium',
      'life insurance',
      'home insurance',
      'renter insurance',
      'renters insurance',
    ],
    category: 'Financial',
    subcategory: 'Insurance',
  },

  // Transfers
  {
    keywords: [
      'transfer',
      'wire transfer',
      'ach payment',
      'ach debit',
      'ach credit',
      'direct deposit',
    ],
    category: 'Transfers',
    subcategory: 'Account Transfer',
  },
  {
    keywords: ['credit card payment', 'card payment'],
    category: 'Transfers',
    subcategory: 'Credit Card Payment',
  },

  // Income
  {
    keywords: ['payroll', 'salary', 'wages', 'direct dep', 'employer'],
    category: 'Income',
    subcategory: 'Salary',
  },
  { keywords: ['dividend'], category: 'Income', subcategory: 'Dividends' },
  {
    keywords: ['interest earned', 'interest income', 'apy'],
    category: 'Income',
    subcategory: 'Interest',
  },
  {
    keywords: ['refund', 'reimbursement', 'cashback', 'cash back'],
    category: 'Income',
    subcategory: 'Refunds',
  },
  {
    keywords: ['freelance', 'consulting fee', '1099'],
    category: 'Income',
    subcategory: 'Freelance',
  },

  // Gifts & Donations
  {
    keywords: ['donation', 'charity', 'nonprofit', 'non-profit', 'charitable'],
    category: 'Gifts & Donations',
    subcategory: 'Charity',
  },
  {
    keywords: ['gift card', 'gift shop', 'flower', 'florist'],
    category: 'Gifts & Donations',
    subcategory: 'Gifts',
  },
];
